on:
  push:

name: Slack notification

jobs:
  send_slack_notification:
    name: Notify the team Slack channel about this release
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Status is bad
        run: |
          cat <<EOF >> $GITHUB_ENV
          SLACK_COLOR=success
          SLACK_MESSAGE=the release is broken(
          EOF
      - name: Send notification
        uses: eugene-babichenko/slack-notifier@master
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK }}
          username: GitHub Actions automated release
          status: ${{ env.SLACK_COLOR  }}
          text: ${{ env.SLACK_MESSAGE  }}
